//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Debugger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Debugger.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments can not be used for a field.
        /// </summary>
        internal static string ArgumentsCantBeUsedForAField {
            get {
                return ResourceManager.GetString("ArgumentsCantBeUsedForAField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad reference.
        /// </summary>
        internal static string BadReference {
            get {
                return ResourceManager.GetString("BadReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not assign {0} to {1}.
        /// </summary>
        internal static string CantAssign {
            get {
                return ResourceManager.GetString("CantAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; can not be set.
        /// </summary>
        internal static string CantBeSet {
            get {
                return ResourceManager.GetString("CantBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not cast {0} to {1}.
        /// </summary>
        internal static string CantCast {
            get {
                return ResourceManager.GetString("CantCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not evaluate after stack overflow.
        /// </summary>
        internal static string CantEvaluateAfterStackOverflow {
            get {
                return ResourceManager.GetString("CantEvaluateAfterStackOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not evaluate because the object is not of proper type.   Expected: {0}  Seen: {1}.
        /// </summary>
        internal static string CantEvaluateObjectNotProperType {
            get {
                return ResourceManager.GetString("CantEvaluateObjectNotProperType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not evaluate in optimized code.
        /// </summary>
        internal static string CantEvaluateOptimizedCode {
            get {
                return ResourceManager.GetString("CantEvaluateOptimizedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not evaluate because the process has no managed stack frames.
        /// </summary>
        internal static string CantEvaluateProcessHasNoManagedStack {
            get {
                return ResourceManager.GetString("CantEvaluateProcessHasNoManagedStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not get value of field.
        /// </summary>
        internal static string CantGetValueOfField {
            get {
                return ResourceManager.GetString("CantGetValueOfField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not implicitely cast {0} to {1}.
        /// </summary>
        internal static string CantImplicitelyCast {
            get {
                return ResourceManager.GetString("CantImplicitelyCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not resolve {0}.
        /// </summary>
        internal static string CantResolve {
            get {
                return ResourceManager.GetString("CantResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not use the binary operator {0} on types {1} and {2}.
        /// </summary>
        internal static string CantuseTheBinaryOperatorOnTypes {
            get {
                return ResourceManager.GetString("CantuseTheBinaryOperatorOnTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not use the unary operator {0} on type {1}.
        /// </summary>
        internal static string CantUseTheUnaryOperatorOnType {
            get {
                return ResourceManager.GetString("CantUseTheUnaryOperatorOnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code must be expression.
        /// </summary>
        internal static string CodeMustBeExpression {
            get {
                return ResourceManager.GetString("CodeMustBeExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code must be expression or statement.
        /// </summary>
        internal static string CodeMustBeExpressionOrStatement {
            get {
                return ResourceManager.GetString("CodeMustBeExpressionOrStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor not found.
        /// </summary>
        internal static string ConstructorNotFound {
            get {
                return ResourceManager.GetString("ConstructorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluating....
        /// </summary>
        internal static string Evaluating {
            get {
                return ResourceManager.GetString("Evaluating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Func eval cannot work. Bad starting point..
        /// </summary>
        internal static string FuncEvalcantWork {
            get {
                return ResourceManager.GetString("FuncEvalcantWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function does not have IL code.
        /// </summary>
        internal static string FunctionDoestHaveILCode {
            get {
                return ResourceManager.GetString("FunctionDoestHaveILCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given indices are out of range of the array.
        /// </summary>
        internal static string GivenIndicesAreOutOfRangeOfTheArray {
            get {
                return ResourceManager.GetString("GivenIndicesAreOutOfRangeOfTheArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given indicies do not have the same dimension as array..
        /// </summary>
        internal static string GivenIndiciesdotHaveSameDimensionAsArray {
            get {
                return ResourceManager.GetString("GivenIndiciesdotHaveSameDimensionAsArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier {0} not found in this context.
        /// </summary>
        internal static string IdentifierNotFound {
            get {
                return ResourceManager.GetString("IdentifierNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect initializer length.
        /// </summary>
        internal static string IncorrectInitializerLength {
            get {
                return ResourceManager.GetString("IncorrectInitializerLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect parameter count.
        /// </summary>
        internal static string IncorrectParameterCount {
            get {
                return ResourceManager.GetString("IncorrectParameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect parameter type for &apos;{0}&apos;. Excpeted {1}, seen {2}.
        /// </summary>
        internal static string IncorrectParameterType {
            get {
                return ResourceManager.GetString("IncorrectParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index was outside the bounds of the array..
        /// </summary>
        internal static string IndexWasOutsideTheBoundsOfTheArray {
            get {
                return ResourceManager.GetString("IndexWasOutsideTheBoundsOfTheArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inncorrect parameter type.
        /// </summary>
        internal static string InncorrectParameterType {
            get {
                return ResourceManager.GetString("InncorrectParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer expected.
        /// </summary>
        internal static string IntegerExpected {
            get {
                return ResourceManager.GetString("IntegerExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid context or thread.
        /// </summary>
        internal static string InvalidContextOrThread {
            get {
                return ResourceManager.GetString("InvalidContextOrThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter count.
        /// </summary>
        internal static string InvalidParameterCount {
            get {
                return ResourceManager.GetString("InvalidParameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is static method and does not have &quot;this&quot;.
        /// </summary>
        internal static string IsStaticMethod {
            get {
                return ResourceManager.GetString("IsStaticMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &quot;{0}&quot; not found.
        /// </summary>
        internal static string MemberNotFound {
            get {
                return ResourceManager.GetString("MemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member reference expected for method invocation.
        /// </summary>
        internal static string MemberReferenceExpected {
            get {
                return ResourceManager.GetString("MemberReferenceExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} not found.
        /// </summary>
        internal static string MethodNotFound {
            get {
                return ResourceManager.GetString("MethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More then one applicable overload found: {0}.
        /// </summary>
        internal static string MoreThenOneApplicableOverloadFound {
            get {
                return ResourceManager.GetString("MoreThenOneApplicableOverloadFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-dimensional arrays are not suppored.
        /// </summary>
        internal static string MultiDimensionalArraysAretSuppored {
            get {
                return ResourceManager.GetString("MultiDimensionalArraysAretSuppored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No applicable overload found.
        /// </summary>
        internal static string NoApplicableOverloadFound {
            get {
                return ResourceManager.GetString("NoApplicableOverloadFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current exception.
        /// </summary>
        internal static string NoCurrentException {
            get {
                return ResourceManager.GetString("NoCurrentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suitable thread for evaluation.
        /// </summary>
        internal static string NoSuitableThreadForEvaluation {
            get {
                return ResourceManager.GetString("NoSuitableThreadForEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available in the current state.
        /// </summary>
        internal static string NotAvailableInTheCurrentState {
            get {
                return ResourceManager.GetString("NotAvailableInTheCurrentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null reference.
        /// </summary>
        internal static string NullReference {
            get {
                return ResourceManager.GetString("NullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object initializers not supported.
        /// </summary>
        internal static string ObjectInitializersNotSupported {
            get {
                return ResourceManager.GetString("ObjectInitializersNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is in wrong AppDomain.
        /// </summary>
        internal static string ObjectInWrongAppDomain {
            get {
                return ResourceManager.GetString("ObjectInWrongAppDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not of type {0}.
        /// </summary>
        internal static string ObjectIstOfType {
            get {
                return ResourceManager.GetString("ObjectIstOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;obj&apos; must be null for constructor call.
        /// </summary>
        internal static string ObjMustBeNull {
            get {
                return ResourceManager.GetString("ObjMustBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overflow.
        /// </summary>
        internal static string Overflow {
            get {
                return ResourceManager.GetString("Overflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primitive value expected.
        /// </summary>
        internal static string PrimitiveValueExpected {
            get {
                return ResourceManager.GetString("PrimitiveValueExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process exited.
        /// </summary>
        internal static string ProcessExited {
            get {
                return ResourceManager.GetString("ProcessExited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property does not have a get method.
        /// </summary>
        internal static string PropertyDoestHaveAGetMethod {
            get {
                return ResourceManager.GetString("PropertyDoestHaveAGetMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single index expected.
        /// </summary>
        internal static string SingleIndexExpected {
            get {
                return ResourceManager.GetString("SingleIndexExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static method does not have &apos;this&apos;..
        /// </summary>
        internal static string StaticMethodDoestHaveThis {
            get {
                return ResourceManager.GetString("StaticMethodDoestHaveThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target object is not a pointer.
        /// </summary>
        internal static string TargetObjectIstAPointer {
            get {
                return ResourceManager.GetString("TargetObjectIstAPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object does not have an indexer property.
        /// </summary>
        internal static string TheObjectDoestHaveIndexerProperty {
            get {
                return ResourceManager.GetString("TheObjectDoestHaveIndexerProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;this&apos; is null.
        /// </summary>
        internal static string ThisIsNull {
            get {
                return ResourceManager.GetString("ThisIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread is in GC unsafe point.
        /// </summary>
        internal static string ThreadIsGCUnsafePoint {
            get {
                return ResourceManager.GetString("ThreadIsGCUnsafePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} expected, {1} seen.
        /// </summary>
        internal static string TypeExpected {
            get {
                return ResourceManager.GetString("TypeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type expected. {0} seen..
        /// </summary>
        internal static string TypeExpectedSeen {
            get {
                return ResourceManager.GetString("TypeExpectedSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable in optimized code.
        /// </summary>
        internal static string UnavailableInOptimizedCode {
            get {
                return ResourceManager.GetString("UnavailableInOptimizedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown operator {0}.
        /// </summary>
        internal static string UnknownOperator {
            get {
                return ResourceManager.GetString("UnknownOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is no longer valid.
        /// </summary>
        internal static string ValueIsNoLongerValid {
            get {
                return ResourceManager.GetString("ValueIsNoLongerValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is null.
        /// </summary>
        internal static string ValueIsNull {
            get {
                return ResourceManager.GetString("ValueIsNull", resourceCulture);
            }
        }
    }
}
